### ISSUE TITLE
BUG: CPU Usage 100%

### ISSUE THREAD

**Issue by Cyber5imon** [tdulcet/System-Usage-Information#2]
Many systems report cpu usage as 100% on the first result when using your method for calculating cpu usage.
The typical workaround for this is to read the cpu stats twice.

I added another `CPU_USAGE=$(cpuusage)` (line 574) directly following the first `CPU_USAGE=$(cpuusage)` and the issue has been resolved.

**Comment by tdulcet** [comment]
My `cpuusage` function does not actually read the CPU usage, it just calculates the usage from the already read raw values, so calling it multiple times will have no effect. Those raw values are already read twice to the `PREVIOUS_STATS` variable on [line 412](https://github.com/tdulcet/System-Usage-Information/blob/master/usage.sh#L412) and then the `STATS` variable on [line 436](https://github.com/tdulcet/System-Usage-Information/blob/master/usage.sh#L436) respectively. The `cpuusage` function then computes the difference between those readings to determine the usage percentage.

If the CPU usage is showing as 100% for you, I would instead try incrementing the sleep value on [line 435](https://github.com/tdulcet/System-Usage-Information/blob/master/usage.sh#L435) to increase the time between the first and second readings. Note that this will of course also increase the runtime for the script. Another potential solution would be to use the experimental/undocumented `-W ` (capital W) option, which will update all the values in an infinite loop until the script is exited, similar to the `top` or `htop` commands.

**Comment by Cyber5imon** [comment]
Thank you for the advise. Like I said in my post, simply adding another `CPU_USAGE=$(cpuusage)` fixed it for me and had no effect on runtime. I was just letting you know as I've seen many other CPU stats programs output 100% on the first iteration and then show correct usage on all following iterations.

**Comment by tdulcet** [comment]
Yes, I have seen that issue in other programs as well... However, my script works as expected for me on all the systems I have used it on:
![image](https://user-images.githubusercontent.com/15305150/213137361-c20d4b3f-7404-43fe-b1c0-7869379a6ed1.png)
I have never seen 100% CPU usage unless it is actually 100%, like with the screenshot on top of the README. Note that this script is more CPU intensive than other programs because it obviously involves running many commands to collect and display all the information, so it may cause a slight CPU spike on some systems.
